/*
    The shared Sisula fixtures, run through dbo.fn_sisulate on this server.

    GENERATED by tests\run-fixtures.ps1 -WriteSqlTest from tests/fixtures in the sisula repository. Do not edit.
    83 cases. Run it in a database where the assembly and dbo.fn_sisulate are installed.

    The first result set lists the cases that fail, if any, then the ones that pass; the second
    counts them. Every case must pass. A case that throws is reported as a failure that says so,
    and the run goes on. The cases about more than ten items check that an array keeps its order,
    which depends on how the rows of OPENJSON are sorted; the emulation used by run-fixtures.ps1
    cannot check that, only a server can.
*/
SET NOCOUNT ON;
DECLARE @results TABLE (id int IDENTITY(1,1), file_name nvarchar(100), case_name nvarchar(400), status varchar(4), expected nvarchar(max), actual nvarchar(max));
DECLARE @t nvarchar(max), @b nvarchar(max), @e nvarchar(max), @a nvarchar(max);

-- comparison.json: >= is true when equal
SET @t = N'$/ if x >= 3' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":3}';
SET @e = N'YES' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'>= is true when equal', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: >= is true when greater
SET @t = N'$/ if x >= 3' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":4}';
SET @e = N'YES' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'>= is true when greater', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: >= is false when less
SET @t = N'$/ if x >= 3' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":2}';
SET @e = N'NO' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'>= is false when less', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: <= is true when equal
SET @t = N'$/ if x <= 3' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":3}';
SET @e = N'YES' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'<= is true when equal', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: <= is true when less
SET @t = N'$/ if x <= 3' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":2}';
SET @e = N'YES' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'<= is true when less', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: <= is false when greater
SET @t = N'$/ if x <= 3' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":4}';
SET @e = N'NO' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'<= is false when greater', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: a single = is the same as ==
SET @t = N'$/ if y = "a"' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"y":"a"}';
SET @e = N'YES' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'a single = is the same as ==', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: a single = is false when different
SET @t = N'$/ if y = "a"' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"y":"b"}';
SET @e = N'NO' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'a single = is false when different', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: != is true when different
SET @t = N'$/ if y != "a"' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"y":"b"}';
SET @e = N'YES' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'!= is true when different', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: the operator inside a quoted string is not an operator
SET @t = N'$/ if y == "a>=b"' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"y":"a>=b"}';
SET @e = N'YES' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'the operator inside a quoted string is not an operator', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: >= in a foreach where
SET @t = N'$/ foreach i in list where i.n >= 2' + NCHAR(10) + N'$i.n$' + NCHAR(10) + N'$/ endfor' + NCHAR(10);
SET @b = N'{"list":[{"n":1},{"n":2},{"n":3}]}';
SET @e = N'2' + NCHAR(10) + N'3' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'>= in a foreach where', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: <= in an inline if
SET @t = N'A$/ if x <= 3 B $/ else C $/ endif D';
SET @b = N'{"x":3}';
SET @e = N'AB D';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'<= in an inline if', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: >= joined with and
SET @t = N'$/ if x >= 3 and x <= 5' + NCHAR(10) + N'IN' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'OUT' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":5}';
SET @e = N'IN' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'>= joined with and', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- comparison.json: >= joined with and, outside the range
SET @t = N'$/ if x >= 3 and x <= 5' + NCHAR(10) + N'IN' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'OUT' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":6}';
SET @e = N'OUT' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'comparison.json', N'>= joined with and, outside the range', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Simple token
SET @t = N'Hello $name$!';
SET @b = N'{"name":"World"}';
SET @e = N'Hello World!';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Simple token', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Nested token
SET @t = N'By: $V.USER$ on $V.COMP$';
SET @b = N'{"V":{"USER":"Lars","COMP":"Mac"}}';
SET @e = N'By: Lars on Mac';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Nested token', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Foreach
SET @t = N'$/ foreach t in tables' + NCHAR(10) + N'-- $t.table$' + NCHAR(10) + N'$/ endfor';
SET @b = N'{"tables":[{"table":"A"},{"table":"B"}]}';
SET @e = N'-- A' + NCHAR(10) + N'-- B' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Foreach', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Foreach order by
SET @t = N'$/ foreach c in columns order by c.ordinal' + NCHAR(10) + N'$c.name$' + NCHAR(10) + N'$/ endfor';
SET @b = N'{"columns":[{"ordinal":3,"name":"C"},{"ordinal":1,"name":"A"},{"ordinal":2,"name":"B"}]}';
SET @e = N'A' + NCHAR(10) + N'B' + NCHAR(10) + N'C' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Foreach order by', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Foreach where
SET @t = N'$/ foreach c in columns where c.ordinal > 1' + NCHAR(10) + N'$c.name$' + NCHAR(10) + N'$/ endfor';
SET @b = N'{"columns":[{"ordinal":1,"name":"A"},{"ordinal":2,"name":"B"},{"ordinal":3,"name":"C"}]}';
SET @e = N'B' + NCHAR(10) + N'C' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Foreach where', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: If/else true
SET @t = N'$/ if x' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif';
SET @b = N'{"x":true}';
SET @e = N'YES' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'If/else true', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: If/else false
SET @t = N'$/ if x' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif';
SET @b = N'{"x":false}';
SET @e = N'NO' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'If/else false', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Loop metadata
SET @t = N'$/ foreach c in columns' + NCHAR(10) + N'$c.index()$: $c.name$ $/ if c.first() (F) $/ endif $/ if c.last() (L) $/ endif' + NCHAR(10) + N'$/ endfor';
SET @b = N'{"columns":[{"name":"A"},{"name":"B"},{"name":"C"}]}';
SET @e = N'0: A (F) ' + NCHAR(10) + N'1: B ' + NCHAR(10) + N'2: C (L) ' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Loop metadata', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Inline if
SET @t = N'$/ foreach c in cols' + NCHAR(10) + N'Col $c.name$ $/ if c.active Active $/ else Inactive $/ endif' + NCHAR(10) + N'$/ endfor';
SET @b = N'{"cols":[{"name":"id","active":true},{"name":"del","active":false}]}';
SET @e = N'Col id Active ' + NCHAR(10) + N'Col del Inactive ' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Inline if', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Line comment
SET @t = N'$- hidden' + NCHAR(10) + N'visible';
SET @b = N'{}';
SET @e = N'visible';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Line comment', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Inline comment
SET @t = N'A $- comment -$ B';
SET @b = N'{}';
SET @e = N'A  B';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Inline comment', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Block mode
SET @t = N'PREFIX /*~' + NCHAR(10) + N'$/ foreach t in tables' + NCHAR(10) + N'-- $t.table$' + NCHAR(10) + N'$/ endfor' + NCHAR(10) + N'~*/ SUFFIX';
SET @b = N'{"tables":[{"table":"A"},{"table":"B"}]}';
SET @e = N'PREFIX ' + NCHAR(10) + N'-- A' + NCHAR(10) + N'-- B' + NCHAR(10) + N' SUFFIX';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Block mode', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: contains()
SET @t = N'$/ foreach c in columns' + NCHAR(10) + N'$/ if contains(c.type,"char")' + NCHAR(10) + N'$c.name$' + NCHAR(10) + N'$/ endif' + NCHAR(10) + N'$/ endfor';
SET @b = N'{"columns":[{"name":"id","type":"int"},{"name":"code","type":"char(20)"}]}';
SET @e = N'code' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'contains()', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: and/or
SET @t = N'$/ foreach item in items where item.price > 50 and item.category == "electronics"' + NCHAR(10) + N'$item.name$' + NCHAR(10) + N'$/ endfor';
SET @b = N'{"items":[{"name":"Laptop","price":999,"category":"electronics"},{"name":"Mouse","price":25,"category":"electronics"}]}';
SET @e = N'Laptop' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'and/or', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Bracket index
SET @t = N'First: $tables[0].table$, Second: $tables[1].table$';
SET @b = N'{"tables":[{"table":"A"},{"table":"B"}]}';
SET @e = N'First: A, Second: B';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Bracket index', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Inline IF OR
SET @t = N'$/ foreach c in columns' + NCHAR(10) + N'-- Found ordinal $c.ordinal$ $/ if c.type = "untyped" or c.type == "varchar(1000) null" with expected type $/ endif' + NCHAR(10) + N'$/ endfor';
SET @b = N'{"columns":[{"ordinal":10,"name":"b","type":"untyped"}]}';
SET @e = N'-- Found ordinal 10 with expected type ' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Inline IF OR', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: startswith
SET @t = N'$/ if startswith(name,"test")' + NCHAR(10) + N'MATCH' + NCHAR(10) + N'$/ endif';
SET @b = N'{"name":"test_table"}';
SET @e = N'MATCH' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'startswith', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: endswith
SET @t = N'$/ if endswith(name,"_table")' + NCHAR(10) + N'MATCH' + NCHAR(10) + N'$/ endif';
SET @b = N'{"name":"test_table"}';
SET @e = N'MATCH' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'endswith', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: count token
SET @t = N'$/ foreach t in tables' + NCHAR(10) + N'Count: $t.count()$' + NCHAR(10) + N'$/ endfor';
SET @b = N'{"tables":[{"table":"A"},{"table":"B"}]}';
SET @e = N'Count: 2' + NCHAR(10) + N'Count: 2' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'count token', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Nested loops
SET @t = N'$/ foreach t in tables' + NCHAR(10) + N'$/ foreach c in t.columns' + NCHAR(10) + N'$t.table$.$c.name$' + NCHAR(10) + N'$/ endfor' + NCHAR(10) + N'$/ endfor';
SET @b = N'{"tables":[{"table":"T1","columns":[{"name":"C1"},{"name":"C2"}]}]}';
SET @e = N'T1.C1' + NCHAR(10) + N'T1.C2' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Nested loops', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: SQL literal quote
SET @t = N'COMMENT = $''d''$';
SET @b = N'{"d":"O''Brien"}';
SET @e = N'COMMENT = ''O''''Brien''';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'SQL literal quote', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: SQL literal newline
SET @t = N'$''d''$';
SET @b = N'{"d":"line1\nline2"}';
SET @e = N'''line1\nline2''';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'SQL literal newline', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: SQL literal backslash
SET @t = N'$''d''$';
SET @b = N'{"d":"a\\b"}';
SET @e = N'''a\\b''';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'SQL literal backslash', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: SQL literal dollar
SET @t = N'$''d''$';
SET @b = N'{"d":"a$b"}';
SET @e = N'''a\x24b''';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'SQL literal dollar', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: SQL literal missing path
SET @t = N'COMMENT = $''nope''$';
SET @b = N'{}';
SET @e = N'COMMENT = ''''';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'SQL literal missing path', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Comment token newline
SET @t = N'-- $|d|$';
SET @b = N'{"d":"line1\nline2"}';
SET @e = N'-- line1 line2';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Comment token newline', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: Comment token dollars
SET @t = N'-- $|d|$';
SET @b = N'{"d":"a$$b"}';
SET @e = N'-- a$ $b';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'Comment token dollars', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- core.json: No rescan of rendered dollars
SET @t = N'$|d|$ and $name$';
SET @b = N'{"d":"$name$","name":"Bob"}';
SET @e = N'$name$ and Bob';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'core.json', N'No rescan of rendered dollars', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not on a path
SET @t = N'$/ if not x' + NCHAR(10) + N'NEG' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'POS' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":true}';
SET @e = N'POS' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not on a path', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not on a false path
SET @t = N'$/ if not x' + NCHAR(10) + N'NEG' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":false}';
SET @e = N'NEG' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not on a false path', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: ! is the same as not
SET @t = N'$/ if !x' + NCHAR(10) + N'NEG' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":false}';
SET @e = N'NEG' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'! is the same as not', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: ! with a space after it
SET @t = N'$/ if ! x' + NCHAR(10) + N'NEG' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":false}';
SET @e = N'NEG' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'! with a space after it', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: != is still a comparison
SET @t = N'$/ if a != b' + NCHAR(10) + N'DIFF' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"a":"1","b":"2"}';
SET @e = N'DIFF' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'!= is still a comparison', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not is case-insensitive
SET @t = N'$/ if NOT x' + NCHAR(10) + N'NEG' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":false}';
SET @e = N'NEG' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not is case-insensitive', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not on a function call
SET @t = N'$/ if not contains(name,"temp")' + NCHAR(10) + N'KEEP' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"name":"real_table"}';
SET @e = N'KEEP' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not on a function call', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not on a comparison negates the whole comparison
SET @t = N'$/ if not a == b' + NCHAR(10) + N'DIFF' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"a":"1","b":"2"}';
SET @e = N'DIFF' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not on a comparison negates the whole comparison', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not binds tighter than and
SET @t = N'$/ if not a and b' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"a":false,"b":true}';
SET @e = N'YES' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not binds tighter than and', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not binds tighter than or
SET @t = N'$/ if not a or b' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"a":true,"b":false}';
SET @e = N'NO' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not binds tighter than or', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not after and
SET @t = N'$/ if a and not b' + NCHAR(10) + N'YES' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NO' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"a":true,"b":false}';
SET @e = N'YES' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not after and', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not on loop metadata as a separator
SET @t = N'$/ foreach i in list' + NCHAR(10) + N'$i.n$$/ if not i.last() ,$/ endif' + NCHAR(10) + N'$/ endfor' + NCHAR(10);
SET @b = N'{"list":[{"n":"a"},{"n":"b"},{"n":"c"}]}';
SET @e = N'a,' + NCHAR(10) + N'b,' + NCHAR(10) + N'c' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not on loop metadata as a separator', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not or last keeps the separator on a historized list
SET @t = N'$/ foreach i in list' + NCHAR(10) + N'$i.n$$/ if not i.last() or tail ,$/ endif' + NCHAR(10) + N'$/ endfor' + NCHAR(10);
SET @b = N'{"tail":true,"list":[{"n":"a"},{"n":"b"}]}';
SET @e = N'a,' + NCHAR(10) + N'b,' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not or last keeps the separator on a historized list', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not in a foreach where
SET @t = N'$/ foreach i in list where not i.hidden' + NCHAR(10) + N'$i.n$' + NCHAR(10) + N'$/ endfor' + NCHAR(10);
SET @b = N'{"list":[{"n":"a","hidden":true},{"n":"b","hidden":false},{"n":"c"}]}';
SET @e = N'b' + NCHAR(10) + N'c' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not in a foreach where', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not in an inline if
SET @t = N'A$/ if not x B $/ else C $/ endif D';
SET @b = N'{"x":false}';
SET @e = N'AB D';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not in an inline if', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not in an inline if, true side of the path
SET @t = N'A$/ if not x B $/ else C $/ endif D';
SET @b = N'{"x":true}';
SET @e = N'AC D';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not in an inline if, true side of the path', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: an empty array is falsy
SET @t = N'$/ if list' + NCHAR(10) + N'HAS' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NONE' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"list":[]}';
SET @e = N'NONE' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'an empty array is falsy', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: a non-empty array is truthy
SET @t = N'$/ if list' + NCHAR(10) + N'HAS' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NONE' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"list":[{"n":"a"}]}';
SET @e = N'HAS' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'a non-empty array is truthy', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: not on an empty array
SET @t = N'$/ if not list' + NCHAR(10) + N'NONE' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"list":[]}';
SET @e = N'NONE' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'not on an empty array', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- negation.json: a condition that cannot be parsed is an error, not false
SET @t = N'$/ if x y z' + NCHAR(10) + N'NEVER' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"x":true}';
SET @e = N'cannot parse condition';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
    INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'a condition that cannot be parsed is an error, not false', 'FAIL', N'error containing ' + @e, @a);
END TRY
BEGIN CATCH
    INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'negation.json', N'a condition that cannot be parsed is an error, not false', CASE WHEN CHARINDEX(@e, ERROR_MESSAGE()) > 0 THEN 'PASS' ELSE 'FAIL' END, N'error containing ' + @e, ERROR_MESSAGE());
END CATCH;

-- nesting.json: an inline if alone on a line inside a block if does not hide the block's else
SET @t = N'$/ if a' + NCHAR(10) + N'  $/ if b X$/ else Y$/ endif' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'Z' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"a":false,"b":true}';
SET @e = N'Z' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'nesting.json', N'an inline if alone on a line inside a block if does not hide the block''s else', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- nesting.json: an inline if alone on a line inside a block if, true branch
SET @t = N'$/ if a' + NCHAR(10) + N'  $/ if b X$/ else Y$/ endif' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'Z' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"a":true,"b":true}';
SET @e = N'  X' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'nesting.json', N'an inline if alone on a line inside a block if, true branch', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- nesting.json: an inline if alone on a line inside a block if, false branch
SET @t = N'$/ if a' + NCHAR(10) + N'  $/ if b X$/ else Y$/ endif' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'Z' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"a":true,"b":false}';
SET @e = N'  Y' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'nesting.json', N'an inline if alone on a line inside a block if, false branch', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- nesting.json: an inline if that closes mid-line inside a block if
SET @t = N'$/ if a' + NCHAR(10) + N'$/ if b X $/ endif tail' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'Z' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"a":true,"b":true}';
SET @e = N'X tail' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'nesting.json', N'an inline if that closes mid-line inside a block if', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- nesting.json: an inline if alone on a line inside a nested block if
SET @t = N'$/ if a' + NCHAR(10) + N'$/ if c' + NCHAR(10) + N'  $/ if b X$/ else Y$/ endif' + NCHAR(10) + N'$/ endif' + NCHAR(10) + N'after' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'Z' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"a":true,"b":false,"c":true}';
SET @e = N'  Y' + NCHAR(10) + N'after' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'nesting.json', N'an inline if alone on a line inside a nested block if', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- nesting.json: an inline foreach alone on a line inside a block foreach
SET @t = N'$/ foreach t in ts' + NCHAR(10) + N'$/ foreach c in t.cs $c.v$,$/ endfor' + NCHAR(10) + N'$/ endfor' + NCHAR(10) + N'done' + NCHAR(10);
SET @b = N'{"ts":[{"cs":[{"v":1},{"v":2}]},{"cs":[{"v":3}]}]}';
SET @e = N'1,2,' + NCHAR(10) + N'3,' + NCHAR(10) + N'done' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'nesting.json', N'an inline foreach alone on a line inside a block foreach', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- ordering.json: a foreach keeps the order of the array when it has more than ten items
SET @t = N'$/ foreach i in list' + NCHAR(10) + N'$i.n$' + NCHAR(10) + N'$/ endfor' + NCHAR(10);
SET @b = N'{"list":[{"n":"a"},{"n":"b"},{"n":"c"},{"n":"d"},{"n":"e"},{"n":"f"},{"n":"g"},{"n":"h"},{"n":"i"},{"n":"j"},{"n":"k"},{"n":"l"}]}';
SET @e = N'a' + NCHAR(10) + N'b' + NCHAR(10) + N'c' + NCHAR(10) + N'd' + NCHAR(10) + N'e' + NCHAR(10) + N'f' + NCHAR(10) + N'g' + NCHAR(10) + N'h' + NCHAR(10) + N'i' + NCHAR(10) + N'j' + NCHAR(10) + N'k' + NCHAR(10) + N'l' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'ordering.json', N'a foreach keeps the order of the array when it has more than ten items', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- ordering.json: an inline foreach keeps the order of the array when it has more than ten items
SET @t = N'$/ foreach i in list $i.n$ $/ endfor';
SET @b = N'{"list":[{"n":0},{"n":1},{"n":2},{"n":3},{"n":4},{"n":5},{"n":6},{"n":7},{"n":8},{"n":9},{"n":10},{"n":11}]}';
SET @e = N'0 1 2 3 4 5 6 7 8 9 10 11 ';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'ordering.json', N'an inline foreach keeps the order of the array when it has more than ten items', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- ordering.json: loop metadata counts through more than ten items
SET @t = N'$/ foreach i in list' + NCHAR(10) + N'$i.index()$/$i.count()$$/ if i.last() !$/ endif' + NCHAR(10) + N'$/ endfor' + NCHAR(10);
SET @b = N'{"list":[{"n":0},{"n":1},{"n":2},{"n":3},{"n":4},{"n":5},{"n":6},{"n":7},{"n":8},{"n":9},{"n":10},{"n":11}]}';
SET @e = N'0/12' + NCHAR(10) + N'1/12' + NCHAR(10) + N'2/12' + NCHAR(10) + N'3/12' + NCHAR(10) + N'4/12' + NCHAR(10) + N'5/12' + NCHAR(10) + N'6/12' + NCHAR(10) + N'7/12' + NCHAR(10) + N'8/12' + NCHAR(10) + N'9/12' + NCHAR(10) + N'10/12' + NCHAR(10) + N'11/12!' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'ordering.json', N'loop metadata counts through more than ten items', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- ordering.json: order by sorts numbers as numbers, not as text
SET @t = N'$/ foreach i in list order by i.n' + NCHAR(10) + N'$i.n$' + NCHAR(10) + N'$/ endfor' + NCHAR(10);
SET @b = N'{"list":[{"n":10},{"n":9},{"n":100},{"n":1},{"n":2}]}';
SET @e = N'1' + NCHAR(10) + N'2' + NCHAR(10) + N'9' + NCHAR(10) + N'10' + NCHAR(10) + N'100' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'ordering.json', N'order by sorts numbers as numbers, not as text', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- ordering.json: order by desc reverses the numeric order
SET @t = N'$/ foreach i in list order by i.n desc' + NCHAR(10) + N'$i.n$' + NCHAR(10) + N'$/ endfor' + NCHAR(10);
SET @b = N'{"list":[{"n":10},{"n":9},{"n":100},{"n":1},{"n":2}]}';
SET @e = N'100' + NCHAR(10) + N'10' + NCHAR(10) + N'9' + NCHAR(10) + N'2' + NCHAR(10) + N'1' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'ordering.json', N'order by desc reverses the numeric order', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- paths.json: an array has no length
SET @t = N'n=$list.length$.';
SET @b = N'{"list":[1,2,3]}';
SET @e = N'n=.';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'paths.json', N'an array has no length', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- paths.json: a string has no length
SET @t = N'n=$s.length$.';
SET @b = N'{"s":"abc"}';
SET @e = N'n=.';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'paths.json', N'a string has no length', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- paths.json: an object property named length is data like any other
SET @t = N'n=$o.length$.';
SET @b = N'{"o":{"length":5}}';
SET @e = N'n=5.';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'paths.json', N'an object property named length is data like any other', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- paths.json: members that every JavaScript object has are not data
SET @t = N'a=$x.constructor$ b=$x.toString$ c=$x.hasOwnProperty$ d=$x.valueOf$.';
SET @b = N'{"x":{"y":1}}';
SET @e = N'a= b= c= d=.';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'paths.json', N'members that every JavaScript object has are not data', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- paths.json: an array has no named members, only elements
SET @t = N'a=$list.first$ b=$list.map$ c=$list[1]$.';
SET @b = N'{"list":["p","q"]}';
SET @e = N'a= b= c=q.';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'paths.json', N'an array has no named members, only elements', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- paths.json: an index past the end of an array is empty
SET @t = N'a=$list[5]$.';
SET @b = N'{"list":["p","q"]}';
SET @e = N'a=.';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'paths.json', N'an index past the end of an array is empty', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- paths.json: an element of an array of objects is reached by index and name
SET @t = N'$items[1].name$';
SET @b = N'{"items":[{"name":"A"},{"name":"B"}]}';
SET @e = N'B';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'paths.json', N'an element of an array of objects is reached by index and name', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- paths.json: an array property of an object is reached through the object
SET @t = N'$o.tags[0]$ and $o.tags[1]$';
SET @b = N'{"o":{"tags":["x","y"]}}';
SET @e = N'x and y';
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'paths.json', N'an array property of an object is reached through the object', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- paths.json: a missing property inside a loop variable is empty
SET @t = N'$/ foreach i in list' + NCHAR(10) + N'[$i.nope$]' + NCHAR(10) + N'$/ endfor' + NCHAR(10);
SET @b = N'{"list":[{"a":1}]}';
SET @e = N'[]' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'paths.json', N'a missing property inside a loop variable is empty', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

-- paths.json: length of an array is not available in a condition either
SET @t = N'$/ if list.length' + NCHAR(10) + N'HAS' + NCHAR(10) + N'$/ else' + NCHAR(10) + N'NONE' + NCHAR(10) + N'$/ endif' + NCHAR(10);
SET @b = N'{"list":[1,2]}';
SET @e = N'NONE' + NCHAR(10);
BEGIN TRY
    SET @a = dbo.fn_sisulate(@t, @b);
END TRY
BEGIN CATCH
    SET @a = N'threw: ' + ERROR_MESSAGE();
END CATCH;
INSERT @results (file_name, case_name, status, expected, actual) VALUES (N'paths.json', N'length of an array is not available in a condition either', CASE WHEN @a COLLATE Latin1_General_BIN2 = @e COLLATE Latin1_General_BIN2 AND DATALENGTH(@a) = DATALENGTH(@e) THEN 'PASS' ELSE 'FAIL' END, @e, @a);

SELECT file_name, case_name, status, expected, actual FROM @results ORDER BY CASE status WHEN 'FAIL' THEN 0 ELSE 1 END, id;
SELECT SUM(CASE WHEN status = 'PASS' THEN 1 ELSE 0 END) AS passed, SUM(CASE WHEN status = 'FAIL' THEN 1 ELSE 0 END) AS failed FROM @results;
